Added RAID 1 Creation on VM startup

diff --git a/roles/vm_creation/templates/user-data-ubuntu.j2 b/roles/vm_creation/templates/user-data-ubuntu.j2
--- a/roles/vm_creation/templates/user-data-ubuntu.j2
+++ b/roles/vm_creation/templates/user-data-ubuntu.j2
@@ -28,6 +28,9 @@ packages:
   - openssh-server
   - sudo
   - python3
+{% if vm_name in ['east_storage', 'west_storage'] %}
+  - mdadm
+{% endif %}
 
 write_files:
   - path: /etc/ssh/sshd_config.d/00-ansible-bootstrap.conf
@@ -40,5 +43,34 @@ write_files:
       KbdInteractiveAuthentication no
 
 runcmd:
+{% if vm_name in ['east_storage', 'west_storage'] %}
+  - |
+      set -eu
+      DISK1=/dev/disk/by-id/virtio-data1
+      DISK2=/dev/disk/by-id/virtio-data2
+
+      while [ ! -e "$DISK1" ] || [ ! -e "$DISK2" ]; do
+        sleep 1
+      done
+
+      if [ ! -e /dev/md0 ]; then
+        mdadm --create /dev/md0 --level=1 --raid-devices=2 "$DISK1" "$DISK2"
+      fi
+
+      if ! blkid /dev/md0 >/dev/null 2>&1; then
+        mkfs.ext4 -L storage /dev/md0
+      fi
+
+      mkdir -p /srv/storage
+      UUID=$(blkid -s UUID -o value /dev/md0)
+
+      if ! grep -q "UUID=$UUID " /etc/fstab; then
+        echo "UUID=$UUID /srv/storage ext4 defaults,nofail 0 2" >> /etc/fstab
+      fi
+
+      mdadm --detail --scan > /etc/mdadm/mdadm.conf
+      update-initramfs -u
+      mount /srv/storage
+{% endif %}
   - [systemctl, enable, --now, ssh]
   - [sh, -c, '/usr/sbin/sshd -t && systemctl reload ssh']
